### ISSUE TITLE
[EP] Value ranges for inspection results

### ISSUE THREAD

**Issue by stiebitzhofer** [thematerials-network/CoA-schemas#40]
## Describe the problem
For some inspections the results is a value range. One example is

**Range of bulk density**     `99.0 .. 100.0`

## Specify the details

1. Add a value type `range` to attribute `ValueType` 

```
"ValueType": {
    "description": "The data type of the measured value.",
    "enum": [
         "string",
         "number",
         "date",
         "date-time",
         "boolean",
         "range"
    ],
    "default": "number"
},
```

2. Specify a pattern for range values for example

`<value_1>;<value_2>`

3. Specify a rendering for example 

`<value_1> .. <value_2>`

### Tasks
- [ ] Implement in schema
- [ ] Add handlebars function
- [ ] Update a JSON fixture to cover the case
- [ ] Update HTML and PDF renderings
- [ ] Update CoA documentation on https://github.com/material-identity/material-identity.github.io

## Explain the benefits
Value ranges for inspection results can be added to CoA in a proper data structure.

**Comment by stiebitzhofer** [comment]
@getlarge Can you please review the requirement and my proposed solution? Thank you!

**Comment by getlarge** [comment]
Since the purpose of our schemas is to allow automated read/write, i’m a bit concerned by the separator that would be used in a range value, should it be declared in another property ? Should there be a unique default ? then how to validate the value  (using a JSON schema validator or in code )?
I didn’t take too much time to think about it, but i would rather modify the type of `Inspection.Value` to be a union of string and array of string with exactly 2 items. Something like :

```json
{
   …  
   "Inspection": {
      "title": "Inspection",
      "description": "A structure to specify any kind of measurements. It follows the structure as defined by CAMPUS (https://www.campusplastics.com)",
      "type": "object",
      "properties": {
        …
        "Value": {
          "description": "A measured or calculated Value (e.g. mean of individual measurements).",
          "oneOf": [
               {  "type": "string" },
               {   
                    "type": "array",  
                    "items": {
                         "type": "string"
                     },
                     "minItems": 2,
                     "maxItems": 2
           ]
        },
        ….
    },
    …
}
```

Or eventually by using the more recent [`prefixItems`](https://json-schema.org/understanding-json-schema/reference/array.html#id7)

**Comment by stiebitzhofer** [comment]
@getlarge I agree, that's how it should be done.

**Comment by stiebitzhofer** [comment]
Will create an issue in the CoA and schema repositories.

**Comment by getlarge** [comment]
do you want to go on with the PR, or should i do it ?

**Comment by stiebitzhofer** [comment]
Do you mean EP? Happy to write the EP in CoA Schemas and link to it in schemas.
